question_data = {
    "response_code": 0,
    "results": [
        {"type": "boolean",
         "difficulty": "easy",
         "category": "General Knowledge",
         "question": "The CEO of tech company Apple following Steve Jobs is named Tim Apple.",
         "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
         "question": "Did Michael Jackson invent the moonwalk?",
         "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean",
         "difficulty": "easy",
         "category": "General Knowledge",
         "question": "&quot;Ananas&quot; is mostly used as the word for Pineapple in other languages.",
         "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean",
         "difficulty": "easy",
         "category": "General Knowledge",
         "question": "You can legally drink alcohol while driving in Mississippi.",
         "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean",
         "difficulty": "easy",
         "category": "General Knowledge",
         "question": "The National Animal of Scotland is the Unicorn.",
         "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean",
         "difficulty": "easy",
         "category": "General Knowledge",
         "question": "Jingle Bells was originally meant for Thanksgiving",
         "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean",
         "difficulty": "easy",
         "category": "General Knowledge",
         "question": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ",
         "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean",
         "difficulty": "easy",
         "category": "General Knowledge",
         "question": "It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.",
         "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean",
         "difficulty": "easy",
         "category": "General Knowledge",
         "question": "Vietnam&#039;s national flag is a red star in front of a yellow background.",
         "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean",
         "difficulty": "easy",
         "category": "General Knowledge",
         "question": "When you cry in space, your tears stick to your face.",
         "correct_answer": "True",
         "incorrect_answers": ["False"]}]}
